pixelquest.setTitle("PIXEL-QUEST")
pixelquest.setWorld(1, tilemap`welt1`, pixelquest.Style.Grass)
pixelquest.setWorld(2, tilemap`welt2`, pixelquest.Style.SciFi)
pixelquest.setWorld(3, tilemap`welt3`, pixelquest.Style.Dungeon)
pixelquest.setLives(3)
pixelquest.setMaxLives(5)
pixelquest.setRunSpeed(80)
pixelquest.setJumpPower(175)
pixelquest.setDoubleJump(true)
pixelquest.setDoubleJumpPower(160)
pixelquest.setGravity(400)
pixelquest.setEnemySpeed(100)
pixelquest.setBossEnergy(20)
pixelquest.setStartWorld(1)
pixelquest.startGame()
